#pragma once

#include "ShaderComponent.h"

class ShaderVisitor
{
public:
	virtual void startVisit(const CBUFFER* pCBUFFER) {};
	virtual void startVisit(const FLOAT4X4* pFLOAT4X4) {};
	virtual void startVisit(const VOID* pVOID) {};
	virtual void startVisit(const FLOAT1* pFLOAT) {};
	virtual void startVisit(const FLOAT2* pFLOAT2) {};
	virtual void startVisit(const FLOAT3* pFLOAT3) {};
	virtual void startVisit(const FLOAT4* pFLOAT4) {};
	virtual void startVisit(const STRUCT* pSTRUCT) {};
	virtual void startVisit(const SEMANTIC* pSEMANTIC) {};
	virtual void startVisit(const SV_POSITION* pSV_POSITION) {};
	virtual void startVisit(const SV_TARGET* pSV_TARGET) {};
	virtual void startVisit(const FUNCTION_DECL* pFUNCTION_DECL) {};
	virtual void startVisit(const FUNCTION_CALL* pFUNCTION_CALL) {};
	virtual void startVisit(const MUL* pMUL) {};
	virtual void startVisit(const FLOAT4_CONSTRUCTOR* pFLOAT4_CONSTRUCTOR) {};
	virtual void startVisit(const SET_VERTEX_SHADER* pSET_VERTEX_SHADER) {};
	virtual void startVisit(const SET_PIXEL_SHADER* pSET_PIXEL_SHADER) {};
	virtual void startVisit(const COMPILE_SHADER* pCOMPILE_SHADER) {};
	virtual void startVisit(const VERTEX_SHADER_VERSION* pVERTEX_SHADER_VERSION) {};
	virtual void startVisit(const PIXEL_SHADER_VERSION* pPIXEL_SHADER_VERSION) {};
	virtual void startVisit(const IN_MODIFIER* pIN) {};
	virtual void startVisit(const OUT_MODIFIER* pOUT) {};
	virtual void startVisit(const INOUT_MODIFIER* pINOUT) {};
	virtual void startVisit(const UNIFORM* pUNIFORM) {};
	virtual void startVisit(const VARIABLE* pVARIABLE) {};
	virtual void startVisit(const VARIABLE_DECL* pVARIABLE_DECL) {};
	virtual void startVisit(const BINARY_MINUS* pBINARY_MINUS) {};
	virtual void startVisit(const BINARY_PLUS* pBINARY_PLUS) {};
	virtual void startVisit(const BINARY_DIVIDE* pBINARY_DIVIDE) {};
	virtual void startVisit(const BINARY_MULTIPLY* pBINARY_MULTIPLY) {};
	virtual void startVisit(const UNARY_MINUS* pUNARY_MINUS) {};
	virtual void startVisit(const UNARY_PLUS* pUNARY_PLUS) {};
	virtual void startVisit(const ASSIGNMENT* pASSIGNMENT) {};
	virtual void startVisit(const TECHNIQUE11* pTECHNIQUE11) {};
	virtual void startVisit(const PASS* pPASS) {};
	virtual void startVisit(const ROUND_BRACKETS* pROUND_BRACKETS) {};
	virtual void startVisit(const SQUARE_BRACKETS* pSQUARE_BRACKETS) {};
	virtual void startVisit(const CURLY_BRACKETS* pCURLY_BRACKETS) {};
	virtual void startVisit(const RETURN* pRETURN) {};
	virtual void startVisit(const SHADER* pSHADER) {};
	virtual void startVisit(const ShaderComponent* pShaderComponent) {};

	virtual void finishVisit(const CBUFFER* pCBUFFER) {};
	virtual void finishVisit(const FLOAT4X4* pFLOAT4X4) {};
	virtual void finishVisit(const VOID* pVOID) {};
	virtual void finishVisit(const FLOAT1* pFLOAT) {};
	virtual void finishVisit(const FLOAT2* pFLOAT2) {};
	virtual void finishVisit(const FLOAT3* pFLOAT3) {};
	virtual void finishVisit(const FLOAT4* pFLOAT4) {};
	virtual void finishVisit(const STRUCT* pSTRUCT) {};
	virtual void finishVisit(const SEMANTIC* pSEMANTIC) {};
	virtual void finishVisit(const SV_POSITION* pSV_POSITION) {};
	virtual void finishVisit(const SV_TARGET* pSV_TARGET) {};
	virtual void finishVisit(const FUNCTION_DECL* pFUNCTION_DECL) {};
	virtual void finishVisit(const FUNCTION_CALL* pFUNCTION_CALL) {};
	virtual void finishVisit(const MUL* pMUL) {};
	virtual void finishVisit(const FLOAT4_CONSTRUCTOR* pFLOAT4_CONSTRUCTOR) {};
	virtual void finishVisit(const SET_VERTEX_SHADER* pSET_VERTEX_SHADER) {};
	virtual void finishVisit(const SET_PIXEL_SHADER* pSET_PIXEL_SHADER) {};
	virtual void finishVisit(const COMPILE_SHADER* pCOMPILE_SHADER) {};
	virtual void finishVisit(const VERTEX_SHADER_VERSION* pVERTEX_SHADER_VERSION) {};
	virtual void finishVisit(const PIXEL_SHADER_VERSION* pPIXEL_SHADER_VERSION) {};
	virtual void finishVisit(const IN_MODIFIER* pIN) {};
	virtual void finishVisit(const OUT_MODIFIER* pOUT) {};
	virtual void finishVisit(const INOUT_MODIFIER* pINOUT) {};
	virtual void finishVisit(const UNIFORM* pUNIFORM) {};
	virtual void finishVisit(const VARIABLE* pVARIABLE) {};
	virtual void finishVisit(const VARIABLE_DECL* pVARIABLE_DECL) {};
	virtual void finishVisit(const BINARY_MINUS* pBINARY_MINUS) {};
	virtual void finishVisit(const BINARY_PLUS* pBINARY_PLUS) {};
	virtual void finishVisit(const BINARY_DIVIDE* pBINARY_DIVIDE) {};
	virtual void finishVisit(const BINARY_MULTIPLY* pBINARY_MULTIPLY) {};
	virtual void finishVisit(const UNARY_MINUS* pUNARY_MINUS) {};
	virtual void finishVisit(const UNARY_PLUS* pUNARY_PLUS) {};
	virtual void finishVisit(const ASSIGNMENT* pASSIGNMENT) {};
	virtual void finishVisit(const TECHNIQUE11* pTECHNIQUE11) {};
	virtual void finishVisit(const PASS* pPASS) {};
	virtual void finishVisit(const ROUND_BRACKETS* pROUND_BRACKETS) {};
	virtual void finishVisit(const SQUARE_BRACKETS* pSQUARE_BRACKETS) {};
	virtual void finishVisit(const CURLY_BRACKETS* pCURLY_BRACKETS) {};
	virtual void finishVisit(const RETURN* pRETURN) {};
	virtual void finishVisit(const SHADER* pSHADER) {};
	virtual void finishVisit(const ShaderComponent* pShaderComponent) {};
};